Do not inject Console.jsm into frame scripts
causes some errors in the browser console

TypeError: console.createInstance is not a function 3 E10SUtils.jsm:297:27
    log resource://gre/modules/E10SUtils.jsm:297
    shouldLoadURI resource://gre/modules/E10SUtils.jsm:955
    shouldLoadURI chrome://browser/content/tab-content.js:45
TypeError: log is not a function LoginManagerChild.jsm:813:8
    onDOMFormHasPassword resource://gre/modules/LoginManagerChild.jsm:813
    handleEvent resource://gre/modules/LoginManagerChild.jsm:673
TypeError: log is undefined LoginFormFactory.jsm:68:5
    createFromForm resource://gre/modules/LoginFormFactory.jsm:68
    createFromField resource://gre/modules/LoginFormFactory.jsm:110
    handleEvent resource://gre/modules/LoginManagerChild.jsm:684